
COUNTRIES_ISO3166_1 = [ {"Code":"AF","Country":"Afghanistan"},
{"Code":"AL","Country":"Albania, People's Socialist Republic of"},
{"Code":"DZ","Country":"Algeria, People's Democratic Republic of"},
{"Code":"AS","Country":"American Samoa"},
{"Code":"AD","Country":"Andorra, Principality of"},
{"Code":"AO","Country":"Angola, Republic of"},
{"Code":"AI","Country":"Anguilla"},
{"Code":"AQ","Country":"Antarctica "},
{"Code":"AG","Country":"Antigua and Barbuda"},
{"Code":"AR","Country":"Argentina, Argentine Republic"},
{"Code":"AM","Country":"Armenia"},
{"Code":"AW","Country":"Aruba"},
{"Code":"AU","Country":"Australia, Commonwealth of"},
{"Code":"AT","Country":"Austria, Republic of"},
{"Code":"AZ","Country":"Azerbaijan, Republic of"},
{"Code":"BS","Country":"Bahamas, Commonwealth of the"},
{"Code":"BH","Country":"Bahrain, Kingdom of"},
{"Code":"BD","Country":"Bangladesh, People's Republic of"},
{"Code":"BB","Country":"Barbados"},
{"Code":"BY","Country":"Belarus"},
{"Code":"BE","Country":"Belgium, Kingdom of"},
{"Code":"BZ","Country":"Belize"},
{"Code":"BJ","Country":"Benin "},
{"Code":"BM","Country":"Bermuda"},
{"Code":"BT","Country":"Bhutan, Kingdom of"},
{"Code":"BO","Country":"Bolivia, Republic of"},
{"Code":"BA","Country":"Bosnia and Herzegovina"},
{"Code":"BW","Country":"Botswana, Republic of"},
{"Code":"BV","Country":"Bouvet Island "},
{"Code":"BR","Country":"Brazil, Federative Republic of"},
{"Code":"IO","Country":"British Indian Ocean Territory "},
{"Code":"VG","Country":"British Virgin Islands"},
{"Code":"BN","Country":"Brunei Darussalam"},
{"Code":"BG","Country":"Bulgaria, People's Republic of"},
{"Code":"BF","Country":"Burkina Faso "},
{"Code":"BI","Country":"Burundi, Republic of"},
{"Code":"KH","Country":"Cambodia, Kingdom of "},
{"Code":"CM","Country":"Cameroon, United Republic of"},
{"Code":"CA","Country":"Canada"},
{"Code":"CV","Country":"Cape Verde, Republic of"},
{"Code":"KY","Country":"Cayman Islands"},
{"Code":"CF","Country":"Central African Republic"},
{"Code":"TD","Country":"Chad, Republic of"},
{"Code":"CL","Country":"Chile, Republic of"},
{"Code":"CN","Country":"China, People's Republic of"},
{"Code":"CX","Country":"Christmas Island"},
{"Code":"CC","Country":"Cocos "},
{"Code":"CO","Country":"Colombia, Republic of"},
{"Code":"KM","Country":"Comoros, Union of the"},
{"Code":"CD","Country":"Congo, Democratic Republic of "},
{"Code":"CG","Country":"Congo, People's Republic of"},
{"Code":"CK","Country":"Cook Islands"},
{"Code":"CR","Country":"Costa Rica, Republic of"},
{"Code":"CI","Country":"Cote D'Ivoire, Ivory Coast, Republic of the"},
{"Code":"CU","Country":"Cuba, Republic of"},
{"Code":"CY","Country":"Cyprus, Republic of"},
{"Code":"CZ","Country":"Czech Republic"},
{"Code":"DK","Country":"Denmark, Kingdom of"},
{"Code":"DJ","Country":"Djibouti, Republic of "},
{"Code":"DM","Country":"Dominica, Commonwealth of"},
{"Code":"DO","Country":"Dominican Republic"},
{"Code":"EC","Country":"Ecuador, Republic of"},
{"Code":"EG","Country":"Egypt, Arab Republic of"},
{"Code":"SV","Country":"El Salvador, Republic of"},
{"Code":"GQ","Country":"Equatorial Guinea, Republic of"},
{"Code":"ER","Country":"Eritrea"},
{"Code":"EE","Country":"Estonia"},
{"Code":"ET","Country":"Ethiopia"},
{"Code":"FO","Country":"Faeroe Islands"},
{"Code":"FK","Country":"Falkland Islands "},
{"Code":"FJ","Country":"Fiji, Republic of the Fiji Islands"},
{"Code":"FI","Country":"Finland, Republic of"},
{"Code":"FR","Country":"France, French Republic"},
{"Code":"GF","Country":"French Guiana"},
{"Code":"PF","Country":"French Polynesia"},
{"Code":"TF","Country":"French Southern Territories"},
{"Code":"GA","Country":"Gabon, Gabonese Republic"},
{"Code":"GM","Country":"Gambia, Republic of the"},
{"Code":"GE","Country":"Georgia"},
{"Code":"DE","Country":"Germany"},
{"Code":"GH","Country":"Ghana, Republic of"},
{"Code":"GI","Country":"Gibraltar"},
{"Code":"GR","Country":"Greece, Hellenic Republic"},
{"Code":"GL","Country":"Greenland"},
{"Code":"GD","Country":"Grenada"},
{"Code":"GP","Country":"Guadaloupe"},
{"Code":"GU","Country":"Guam"},
{"Code":"GT","Country":"Guatemala, Republic of"},
{"Code":"GN","Country":"Guinea, Revolutionary People's Rep'c of"},
{"Code":"GW","Country":"Guinea-Bissau, Republic of "},
{"Code":"GY","Country":"Guyana, Republic of"},
{"Code":"HT","Country":"Haiti, Republic of"},
{"Code":"HM","Country":"Heard and McDonald Islands"},
{"Code":"VA","Country":"Holy See "},
{"Code":"HN","Country":"Honduras, Republic of"},
{"Code":"HK","Country":"Hong Kong, Special Administrative Region of China"},
{"Code":"HR","Country":"Hrvatska "},
{"Code":"HU","Country":"Hungary, Hungarian People's Republic"},
{"Code":"IS","Country":"Iceland, Republic of"},
{"Code":"IN","Country":"India, Republic of"},
{"Code":"ID","Country":"Indonesia, Republic of"},
{"Code":"IR","Country":"Iran, Islamic Republic of"},
{"Code":"IQ","Country":"Iraq, Republic of"},
{"Code":"IE","Country":"Ireland"},
{"Code":"IL","Country":"Israel, State of"},
{"Code":"IT","Country":"Italy, Italian Republic"},
{"Code":"JM","Country":"Jamaica"},
{"Code":"JP","Country":"Japan"},
{"Code":"JO","Country":"Jordan, Hashemite Kingdom of"},
{"Code":"KZ","Country":"Kazakhstan, Republic of"},
{"Code":"KE","Country":"Kenya, Republic of"},
{"Code":"KI","Country":"Kiribati, Republic of "},
{"Code":"KP","Country":"Korea, Democratic People's Republic of"},
{"Code":"KR","Country":"Korea, Republic of"},
{"Code":"KW","Country":"Kuwait, State of"},
{"Code":"KG","Country":"Kyrgyz Republic"},
{"Code":"LA","Country":"Lao People's Democratic Republic"},
{"Code":"LV","Country":"Latvia"},
{"Code":"LB","Country":"Lebanon, Lebanese Republic"},
{"Code":"LS","Country":"Lesotho, Kingdom of"},
{"Code":"LR","Country":"Liberia, Republic of"},
{"Code":"LY","Country":"Libyan Arab Jamahiriya"},
{"Code":"LI","Country":"Liechtenstein, Principality of"},
{"Code":"LT","Country":"Lithuania"},
{"Code":"LU","Country":"Luxembourg, Grand Duchy of"},
{"Code":"MO","Country":"Macao, Special Administrative Region of China"},
{"Code":"MK","Country":"Macedonia, the former Yugoslav Republic of"},
{"Code":"MG","Country":"Madagascar, Republic of"},
{"Code":"MW","Country":"Malawi, Republic of"},
{"Code":"MY","Country":"Malaysia"},
{"Code":"MV","Country":"Maldives, Republic of"},
{"Code":"ML","Country":"Mali, Republic of"},
{"Code":"MT","Country":"Malta, Republic of"},
{"Code":"MH","Country":"Marshall Islands"},
{"Code":"MQ","Country":"Martinique"},
{"Code":"MR","Country":"Mauritania, Islamic Republic of"},
{"Code":"MU","Country":"Mauritius"},
{"Code":"YT","Country":"Mayotte"},
{"Code":"MX","Country":"Mexico, United Mexican States"},
{"Code":"FM","Country":"Micronesia, Federated States of"},
{"Code":"MD","Country":"Moldova, Republic of"},
{"Code":"MC","Country":"Monaco, Principality of"},
{"Code":"MN","Country":"Mongolia, Mongolian People's Republic"},
{"Code":"MS","Country":"Montserrat"},
{"Code":"MA","Country":"Morocco, Kingdom of"},
{"Code":"MZ","Country":"Mozambique, People's Republic of"},
{"Code":"MM","Country":"Myanmar "},
{"Code":"NA","Country":"Namibia"},
{"Code":"NR","Country":"Nauru, Republic of"},
{"Code":"NP","Country":"Nepal, Kingdom of"},
{"Code":"AN","Country":"Netherlands Antilles"},
{"Code":"NL","Country":"Netherlands, Kingdom of the"},
{"Code":"NC","Country":"New Caledonia"},
{"Code":"NZ","Country":"New Zealand"},
{"Code":"NI","Country":"Nicaragua, Republic of"},
{"Code":"NE","Country":"Niger, Republic of the"},
{"Code":"NG","Country":"Nigeria, Federal Republic of"},
{"Code":"NU","Country":"Niue, Republic of"},
{"Code":"NF","Country":"Norfolk Island"},
{"Code":"MP","Country":"Northern Mariana Islands"},
{"Code":"NO","Country":"Norway, Kingdom of"},
{"Code":"OM","Country":"Oman, Sultanate of "},
{"Code":"PK","Country":"Pakistan, Islamic Republic of"},
{"Code":"PW","Country":"Palau"},
{"Code":"PS","Country":"Palestinian Territory, Occupied"},
{"Code":"PA","Country":"Panama, Republic of"},
{"Code":"PG","Country":"Papua New Guinea"},
{"Code":"PY","Country":"Paraguay, Republic of"},
{"Code":"PE","Country":"Peru, Republic of"},
{"Code":"PH","Country":"Philippines, Republic of the"},
{"Code":"PN","Country":"Pitcairn Island"},
{"Code":"PL","Country":"Poland, Polish People's Republic"},
{"Code":"PT","Country":"Portugal, Portuguese Republic"},
{"Code":"PR","Country":"Puerto Rico"},
{"Code":"QA","Country":"Qatar, State of"},
{"Code":"RE","Country":"Reunion"},
{"Code":"RO","Country":"Romania, Socialist Republic of"},
{"Code":"RU","Country":"Russian Federation"},
{"Code":"RW","Country":"Rwanda, Rwandese Republic"},
{"Code":"SH","Country":"St. Helena"},
{"Code":"KN","Country":"St. Kitts and Nevis"},
{"Code":"LC","Country":"St. Lucia"},
{"Code":"PM","Country":"St. Pierre and Miquelon"},
{"Code":"VC","Country":"St. Vincent and the Grenadines"},
{"Code":"WS","Country":"Samoa, Independent State of "},
{"Code":"SM","Country":"San Marino, Republic of"},
{"Code":"ST","Country":"Sao Tome and Principe, Democratic Republic of"},
{"Code":"SA","Country":"Saudi Arabia, Kingdom of"},
{"Code":"SN","Country":"Senegal, Republic of"},
{"Code":"CS","Country":"Serbia and Montenegro"},
{"Code":"SC","Country":"Seychelles, Republic of"},
{"Code":"SL","Country":"Sierra Leone, Republic of"},
{"Code":"SG","Country":"Singapore, Republic of"},
{"Code":"SK","Country":"Slovakia "},
{"Code":"SI","Country":"Slovenia"},
{"Code":"SB","Country":"Solomon Islands "},
{"Code":"SO","Country":"Somalia, Somali Republic"},
{"Code":"ZA","Country":"South Africa, Republic of"},
{"Code":"GS","Country":"South Georgia and the South Sandwich Islands"},
{"Code":"ES","Country":"Spain, Spanish State"},
{"Code":"LK","Country":"Sri Lanka, Democratic Socialist Republic of "},
{"Code":"SD","Country":"Sudan, Democratic Republic of the"},
{"Code":"SR","Country":"Suriname, Republic of"},
{"Code":"SJ","Country":"Svalbard & Jan Mayen Islands"},
{"Code":"SZ","Country":"Swaziland, Kingdom of"},
{"Code":"SE","Country":"Sweden, Kingdom of"},
{"Code":"CH","Country":"Switzerland, Swiss Confederation"},
{"Code":"SY","Country":"Syrian Arab Republic"},
{"Code":"TW","Country":"Taiwan, Province of China"},
{"Code":"TJ","Country":"Tajikistan"},
{"Code":"TZ","Country":"Tanzania, United Republic of"},
{"Code":"TH","Country":"Thailand, Kingdom of"},
{"Code":"TL","Country":"Timor-Leste, Democratic Republic of"},
{"Code":"TG","Country":"Togo, Togolese Republic"},
{"Code":"TK","Country":"Tokelau "},
{"Code":"TO","Country":"Tonga, Kingdom of"},
{"Code":"TT","Country":"Trinidad and Tobago, Republic of"},
{"Code":"TN","Country":"Tunisia, Republic of"},
{"Code":"TR","Country":"Turkey, Republic of"},
{"Code":"TM","Country":"Turkmenistan"},
{"Code":"TC","Country":"Turks and Caicos Islands"},
{"Code":"TV","Country":"Tuvalu "},
{"Code":"VI","Country":"US Virgin Islands"},
{"Code":"UG","Country":"Uganda, Republic of"},
{"Code":"UA","Country":"Ukraine"},
{"Code":"AE","Country":"United Arab Emirates "},
{"Code":"GB","Country":"United Kingdom of Great Britain & N. Ireland"},
{"Code":"UM","Country":"United States Minor Outlying Islands"},
{"Code":"US","Country":"United States of America"},
{"Code":"UY","Country":"Uruguay, Eastern Republic of"},
{"Code":"UZ","Country":"Uzbekistan"},
{"Code":"VU","Country":"Vanuatu "},
{"Code":"VE","Country":"Venezuela, Bolivarian Republic of"},
{"Code":"VN","Country":"Viet Nam, Socialist Republic of "},
{"Code":"WF","Country":"Wallis and Futuna Islands"},
{"Code":"EH","Country":"Western Sahara "},
{"Code":"YE","Country":"Yemen"},
{"Code":"ZM","Country":"Zambia, Republic of"},
{"Code":"ZW","Country":"Zimbabwe "},
]


LANGUAGES_ISO639_1 = [ {"Code": "aa", "Name": "Afar"},
{"Code": "ab", "Name": "Abkhazian"},
{"Code": "ae", "Name": "Avestan"},
{"Code": "af", "Name": "Afrikaans"},
{"Code": "ak", "Name": "Akan"},
{"Code": "am", "Name": "Amharic"},
{"Code": "an", "Name": "Aragonese"},
{"Code": "ar", "Name": "Arabic"},
{"Code": "as", "Name": "Assamese"},
{"Code": "av", "Name": "Avaric"},
{"Code": "ay", "Name": "Aymara"},
{"Code": "az", "Name": "Azerbaijani"},
{"Code": "ba", "Name": "Bashkir"},
{"Code": "be", "Name": "Belarusian"},
{"Code": "bg", "Name": "Bulgarian"},
{"Code": "bh", "Name": "languages"},
{"Code": "bi", "Name": "Bislama"},
{"Code": "bm", "Name": "Bambara"},
{"Code": "bn", "Name": "Bengali"},
{"Code": "bo", "Name": "Tibetan"},
{"Code": "br", "Name": "Breton"},
{"Code": "bs", "Name": "Bosnian"},
{"Code": "ca", "Name": "Catalan"},
{"Code": "ce", "Name": "Chechen"},
{"Code": "ch", "Name": "Chamorro"},
{"Code": "co", "Name": "Corsican"},
{"Code": "cr", "Name": "Cree"},
{"Code": "cs", "Name": "Czech"},
{"Code": "cu", "Name": "Church"},
{"Code": "cv", "Name": "Chuvash"},
{"Code": "cy", "Name": "Welsh"},
{"Code": "da", "Name": "Danish"},
{"Code": "de", "Name": "German"},
{"Code": "dv", "Name": "Dhivehi"},
{"Code": "dz", "Name": "Dzongkha"},
{"Code": "ee", "Name": "Ewe"},
{"Code": "el", "Name": "Greek"},
{"Code": "en", "Name": "English"},
{"Code": "eo", "Name": "Esperanto"},
{"Code": "es", "Name": "Spanish"},
{"Code": "et", "Name": "Estonian"},
{"Code": "eu", "Name": "Basque"},
{"Code": "fa", "Name": "Persian"},
{"Code": "ff", "Name": "Fulah"},
{"Code": "fi", "Name": "Finnish"},
{"Code": "fj", "Name": "Fijian"},
{"Code": "fo", "Name": "Faroese"},
{"Code": "fr", "Name": "French"},
{"Code": "fy", "Name": "Western"},
{"Code": "ga", "Name": "Irish"},
{"Code": "gd", "Name": "Scottish"},
{"Code": "gl", "Name": "Galician"},
{"Code": "gn", "Name": "Guarani"},
{"Code": "gu", "Name": "Gujarati"},
{"Code": "gv", "Name": "Manx"},
{"Code": "ha", "Name": "Hausa"},
{"Code": "he", "Name": "Hebrew"},
{"Code": "hi", "Name": "Hindi"},
{"Code": "ho", "Name": "Hiri"},
{"Code": "hr", "Name": "Croatian"},
{"Code": "ht", "Name": "Haitian"},
{"Code": "hu", "Name": "Hungarian"},
{"Code": "hy", "Name": "Armenian"},
{"Code": "hz", "Name": "Herero"},
{"Code": "ia", "Name": "Interlingua"},
{"Code": "id", "Name": "Indonesian"},
{"Code": "ie", "Name": "Interlingue"},
{"Code": "ig", "Name": "Igbo"},
{"Code": "ii", "Name": "Sichuan"},
{"Code": "ik", "Name": "Inupiaq"},
{"Code": "io", "Name": "Ido"},
{"Code": "is", "Name": "Icelandic"},
{"Code": "it", "Name": "Italian"},
{"Code": "iu", "Name": "Inuktitut"},
{"Code": "ja", "Name": "Japanese"},
{"Code": "jv", "Name": "Javanese"},
{"Code": "ka", "Name": "Georgian"},
{"Code": "kg", "Name": "Kongo"},
{"Code": "ki", "Name": "Kikuyu"},
{"Code": "kj", "Name": "Kuanyama"},
{"Code": "kk", "Name": "Kazakh"},
{"Code": "kl", "Name": "Kalaallisut"},
{"Code": "km", "Name": "Central"},
{"Code": "kn", "Name": "Kannada"},
{"Code": "ko", "Name": "Korean"},
{"Code": "kr", "Name": "Kanuri"},
{"Code": "ks", "Name": "Kashmiri"},
{"Code": "ku", "Name": "Kurdish"},
{"Code": "kv", "Name": "Komi"},
{"Code": "kw", "Name": "Cornish"},
{"Code": "ky", "Name": "Kirghiz"},
{"Code": "la", "Name": "Latin"},
{"Code": "lb", "Name": "Luxembourgish"},
{"Code": "lg", "Name": "Ganda"},
{"Code": "li", "Name": "Limburgan"},
{"Code": "ln", "Name": "Lingala"},
{"Code": "lo", "Name": "Lao"},
{"Code": "lt", "Name": "Lithuanian"},
{"Code": "lu", "Name": "Luba-Katanga"},
{"Code": "lv", "Name": "Latvian"},
{"Code": "mg", "Name": "Malagasy"},
{"Code": "mh", "Name": "Marshallese"},
{"Code": "mi", "Name": "Maori"},
{"Code": "mk", "Name": "Macedonian"},
{"Code": "ml", "Name": "Malayalam"},
{"Code": "mn", "Name": "Mongolian"},
{"Code": "mr", "Name": "Marathi"},
{"Code": "ms", "Name": "Malay"},
{"Code": "mt", "Name": "Maltese"},
{"Code": "my", "Name": "Burmese"},
{"Code": "na", "Name": "Nauru"},
{"Code": "nb", "Name": "Norwegian"},
{"Code": "nd", "Name": "North"},
{"Code": "ne", "Name": "Nepali"},
{"Code": "ng", "Name": "Ndonga"},
{"Code": "nl", "Name": "Dutch"},
{"Code": "nn", "Name": "Norwegian"},
{"Code": "no", "Name": "Norwegian"},
{"Code": "nr", "Name": "South"},
{"Code": "nv", "Name": "Navajo"},
{"Code": "ny", "Name": "Nyanja"},
{"Code": "oc", "Name": "Occitan"},
{"Code": "oj", "Name": "Ojibwa"},
{"Code": "om", "Name": "Oromo"},
{"Code": "or", "Name": "Oriya"},
{"Code": "os", "Name": "Ossetian"},
{"Code": "pa", "Name": "Panjabi"},
{"Code": "pi", "Name": "Pali"},
{"Code": "pl", "Name": "Polish"},
{"Code": "ps", "Name": "Pushto"},
{"Code": "pt", "Name": "Portuguese"},
{"Code": "qu", "Name": "Quechua"},
{"Code": "rm", "Name": "Romansh"},
{"Code": "rn", "Name": "Rundi"},
{"Code": "ro", "Name": "Romanian"},
{"Code": "ru", "Name": "Russian"},
{"Code": "rw", "Name": "Kinyarwanda"},
{"Code": "sa", "Name": "Sanskrit"},
{"Code": "sc", "Name": "Sardinian"},
{"Code": "sd", "Name": "Sindhi"},
{"Code": "se", "Name": "Northern"},
{"Code": "sg", "Name": "Sango"},
{"Code": "sh", "Name": "Serbo-Croatian"},
{"Code": "si", "Name": "Sinhala"},
{"Code": "sk", "Name": "Slovak"},
{"Code": "sl", "Name": "Slovenian"},
{"Code": "sm", "Name": "Samoan"},
{"Code": "sn", "Name": "Shona"},
{"Code": "so", "Name": "Somali"},
{"Code": "sq", "Name": "Albanian"},
{"Code": "sr", "Name": "Serbian"},
{"Code": "ss", "Name": "Swati"},
{"Code": "st", "Name": "Southern"},
{"Code": "su", "Name": "Sundanese"},
{"Code": "sv", "Name": "Swedish"},
{"Code": "sw", "Name": "Swahili"},
{"Code": "ta", "Name": "Tamil"},
{"Code": "te", "Name": "Telugu"},
{"Code": "tg", "Name": "Tajik"},
{"Code": "th", "Name": "Thai"},
{"Code": "ti", "Name": "Tigrinya"},
{"Code": "tk", "Name": "Turkmen"},
{"Code": "tl", "Name": "Tagalog"},
{"Code": "tn", "Name": "Tswana"},
{"Code": "to", "Name": "Tonga"},
{"Code": "tr", "Name": "Turkish"},
{"Code": "ts", "Name": "Tsonga"},
{"Code": "tt", "Name": "Tatar"},
{"Code": "tw", "Name": "Twi"},
{"Code": "ty", "Name": "Tahitian"},
{"Code": "ug", "Name": "Uighur"},
{"Code": "uk", "Name": "Ukrainian"},
{"Code": "ur", "Name": "Urdu"},
{"Code": "uz", "Name": "Uzbek"},
{"Code": "ve", "Name": "Venda"},
{"Code": "vi", "Name": "Vietnamese"},
{"Code": "vo", "Name": "Volap"},
{"Code": "wa", "Name": "Walloon"},
{"Code": "wo", "Name": "Wolof"},
{"Code": "xh", "Name": "Xhosa"},
{"Code": "yi", "Name": "Yiddish"},
{"Code": "yo", "Name": "Yoruba"},
{"Code": "za", "Name": "Zhuang"},
{"Code": "zh", "Name": "Chinese"},
{"Code": "zu", "Name": "Zulu"}
]
