
COUNTRIES_ISO3166_1 = [ {"Code": "AC", "Country": "Ascension Island"},
{"Code": "AC", "Country": "ANDORRA"},
{"Code": "AC", "Country": "UNITED ARAB EMIRATES"},
{"Code": "AC", "Country": "AFGHANISTAN"},
{"Code": "AC", "Country": "ANTIGUA AND BARBUDA"},
{"Code": "AC", "Country": "ANGUILLA"},
{"Code": "AC", "Country": "ALBANIA"},
{"Code": "AC", "Country": "ARMENIA"},
{"Code": "AC", "Country": "Netherlands Antilles"},
{"Code": "AC", "Country": "ANGOLA"},
{"Code": "AC", "Country": "ANTARCTICA"},
{"Code": "AC", "Country": "ARGENTINA"},
{"Code": "AC", "Country": "AMERICAN SAMOA"},
{"Code": "AC", "Country": "AUSTRIA"},
{"Code": "AC", "Country": "AUSTRALIA"},
{"Code": "AC", "Country": "ARUBA"},
{"Code": "AC", "Country": "AAND ISLANDS"},
{"Code": "AC", "Country": "AZERBAIJAN"},
{"Code": "AC", "Country": "BOSNIA AND HERZEGOVINA"},
{"Code": "AC", "Country": "BARBADOS"},
{"Code": "AC", "Country": "BANGLADESH"},
{"Code": "AC", "Country": "BELGIUM"},
{"Code": "AC", "Country": "BURKINA FASO"},
{"Code": "AC", "Country": "BULGARIA"},
{"Code": "AC", "Country": "BAHRAIN"},
{"Code": "AC", "Country": "BURUNDI"},
{"Code": "AC", "Country": "BENIN"},
{"Code": "AC", "Country": "SAINT BARTHOEMY"},
{"Code": "AC", "Country": "BERMUDA"},
{"Code": "AC", "Country": "BRUNEI DARUSSALAM"},
{"Code": "AC", "Country": "BOLIVIA, PLURINATIONAL STATE OF"},
{"Code": "AC", "Country": "BONAIRE, SINT EUSTATIUS AND SABA"},
{"Code": "AC", "Country": "BRAZIL"},
{"Code": "AC", "Country": "BAHAMAS"},
{"Code": "AC", "Country": "BHUTAN"},
{"Code": "AC", "Country": "Burma"},
{"Code": "AC", "Country": "BOUVET ISLAND"},
{"Code": "AC", "Country": "BOTSWANA"},
{"Code": "AC", "Country": "BELARUS"},
{"Code": "AC", "Country": "BELIZE"},
{"Code": "AC", "Country": "CANADA"},
{"Code": "AC", "Country": "COCOS (KEELING) ISLANDS"},
{"Code": "AC", "Country": "CONGO, THE DEMOCRATIC REPUBLIC OF THE"},
{"Code": "AC", "Country": "CENTRAL AFRICAN REPUBLIC"},
{"Code": "AC", "Country": "CONGO"},
{"Code": "AC", "Country": "SWITZERLAND"},
{"Code": "AC", "Country": "CUE D'IVOIRE"},
{"Code": "AC", "Country": "COOK ISLANDS"},
{"Code": "AC", "Country": "CHILE"},
{"Code": "AC", "Country": "CAMEROON"},
{"Code": "AC", "Country": "CHINA"},
{"Code": "AC", "Country": "COLOMBIA"},
{"Code": "AC", "Country": "Clipperton Island"},
{"Code": "AC", "Country": "COSTA RICA"},
{"Code": "AC", "Country": "SERBIA AND MONTENEGRO"},
{"Code": "AC", "Country": "CUBA"},
{"Code": "AC", "Country": "CAPE VERDE"},
{"Code": "AC", "Country": "CURAGO"},
{"Code": "AC", "Country": "CHRISTMAS ISLAND"},
{"Code": "AC", "Country": "CYPRUS"},
{"Code": "AC", "Country": "CZECH REPUBLIC"},
{"Code": "AC", "Country": "GERMANY"},
{"Code": "AC", "Country": "Diego Garcia"},
{"Code": "AC", "Country": "DJIBOUTI"},
{"Code": "AC", "Country": "DENMARK"},
{"Code": "AC", "Country": "DOMINICA"},
{"Code": "AC", "Country": "DOMINICAN REPUBLIC"},
{"Code": "AC", "Country": "ALGERIA"},
{"Code": "AC", "Country": "ECUADOR"},
{"Code": "AC", "Country": "ESTONIA"},
{"Code": "AC", "Country": "Union of Countries under the European Community Patent Convention"},
{"Code": "AC", "Country": "EGYPT"},
{"Code": "AC", "Country": "WESTERN SAHARA"},
{"Code": "AC", "Country": "European Patent Organization"},
{"Code": "AC", "Country": "ERITREA"},
{"Code": "AC", "Country": "SPAIN"},
{"Code": "AC", "Country": "ETHIOPIA"},
{"Code": "AC", "Country": "European Union"},
{"Code": "AC", "Country": "Estonia"},
{"Code": "AC", "Country": "FINLAND"},
{"Code": "AC", "Country": "FIJI"},
{"Code": "AC", "Country": "FALKLAND ISLANDS (MALVINAS)"},
{"Code": "AC", "Country": "Liechtenstein"},
{"Code": "AC", "Country": "MICRONESIA, FEDERATED STATES OF"},
{"Code": "AC", "Country": "FAROE ISLANDS"},
{"Code": "AC", "Country": "FRANCE"},
{"Code": "AC", "Country": "France, Metropolitan"},
{"Code": "AC", "Country": "GABON"},
{"Code": "AC", "Country": "UNITED KINGDOM"},
{"Code": "AC", "Country": "GRENADA"},
{"Code": "AC", "Country": "GEORGIA"},
{"Code": "AC", "Country": "FRENCH GUIANA"},
{"Code": "AC", "Country": "GUERNSEY"},
{"Code": "AC", "Country": "GHANA"},
{"Code": "AC", "Country": "GIBRALTAR"},
{"Code": "AC", "Country": "GREENLAND"},
{"Code": "AC", "Country": "GAMBIA"},
{"Code": "AC", "Country": "GUINEA"},
{"Code": "AC", "Country": "GUADELOUPE"},
{"Code": "AC", "Country": "EQUATORIAL GUINEA"},
{"Code": "AC", "Country": "GREECE"},
{"Code": "AC", "Country": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"},
{"Code": "AC", "Country": "GUATEMALA"},
{"Code": "AC", "Country": "GUAM"},
{"Code": "AC", "Country": "GUINEA-BISSAU"},
{"Code": "AC", "Country": "GUYANA"},
{"Code": "AC", "Country": "HONG KONG"},
{"Code": "AC", "Country": "HEARD ISLAND AND MCDONALD ISLANDS"},
{"Code": "AC", "Country": "HONDURAS"},
{"Code": "AC", "Country": "CROATIA"},
{"Code": "AC", "Country": "HAITI"},
{"Code": "AC", "Country": "HUNGARY"},
{"Code": "AC", "Country": "Canary Islands"},
{"Code": "AC", "Country": "INDONESIA"},
{"Code": "AC", "Country": "IRELAND"},
{"Code": "AC", "Country": "ISRAEL"},
{"Code": "AC", "Country": "ISLE OF MAN"},
{"Code": "AC", "Country": "INDIA"},
{"Code": "AC", "Country": "BRITISH INDIAN OCEAN TERRITORY"},
{"Code": "AC", "Country": "IRAQ"},
{"Code": "AC", "Country": "IRAN, ISLAMIC REPUBLIC OF"},
{"Code": "AC", "Country": "ICELAND"},
{"Code": "AC", "Country": "ITALY"},
{"Code": "AC", "Country": "JERSEY"},
{"Code": "AC", "Country": "JAMAICA"},
{"Code": "AC", "Country": "JORDAN"},
{"Code": "AC", "Country": "JAPAN"},
{"Code": "AC", "Country": "KENYA"},
{"Code": "AC", "Country": "KYRGYZSTAN"},
{"Code": "AC", "Country": "CAMBODIA"},
{"Code": "AC", "Country": "KIRIBATI"},
{"Code": "AC", "Country": "COMOROS"},
{"Code": "AC", "Country": "SAINT KITTS AND NEVIS"},
{"Code": "AC", "Country": "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"},
{"Code": "AC", "Country": "KOREA, REPUBLIC OF"},
{"Code": "AC", "Country": "KUWAIT"},
{"Code": "AC", "Country": "CAYMAN ISLANDS"},
{"Code": "AC", "Country": "KAZAKHSTAN"},
{"Code": "AC", "Country": "LAO PEOPLE'S DEMOCRATIC REPUBLIC"},
{"Code": "AC", "Country": "LEBANON"},
{"Code": "AC", "Country": "SAINT LUCIA"},
{"Code": "AC", "Country": "Libya Fezzan"},
{"Code": "AC", "Country": "LIECHTENSTEIN"},
{"Code": "AC", "Country": "SRI LANKA"},
{"Code": "AC", "Country": "LIBERIA"},
{"Code": "AC", "Country": "LESOTHO"},
{"Code": "AC", "Country": "LITHUANIA"},
{"Code": "AC", "Country": "LUXEMBOURG"},
{"Code": "AC", "Country": "LATVIA"},
{"Code": "AC", "Country": "LIBYA"},
{"Code": "AC", "Country": "MOROCCO"},
{"Code": "AC", "Country": "MONACO"},
{"Code": "AC", "Country": "MOLDOVA, REPUBLIC OF"},
{"Code": "AC", "Country": "MONTENEGRO"},
{"Code": "AC", "Country": "SAINT MARTIN (FRENCH PART)"},
{"Code": "AC", "Country": "MADAGASCAR"},
{"Code": "AC", "Country": "MARSHALL ISLANDS"},
{"Code": "AC", "Country": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"},
{"Code": "AC", "Country": "MALI"},
{"Code": "AC", "Country": "MYANMAR"},
{"Code": "AC", "Country": "MONGOLIA"},
{"Code": "AC", "Country": "MACAO"},
{"Code": "AC", "Country": "NORTHERN MARIANA ISLANDS"},
{"Code": "AC", "Country": "MARTINIQUE"},
{"Code": "AC", "Country": "MAURITANIA"},
{"Code": "AC", "Country": "MONTSERRAT"},
{"Code": "AC", "Country": "MALTA"},
{"Code": "AC", "Country": "MAURITIUS"},
{"Code": "AC", "Country": "MALDIVES"},
{"Code": "AC", "Country": "MALAWI"},
{"Code": "AC", "Country": "MEXICO"},
{"Code": "AC", "Country": "MALAYSIA"},
{"Code": "AC", "Country": "MOZAMBIQUE"},
{"Code": "AC", "Country": "NAMIBIA"},
{"Code": "AC", "Country": "NEW CALEDONIA"},
{"Code": "AC", "Country": "NIGER"},
{"Code": "AC", "Country": "NORFOLK ISLAND"},
{"Code": "AC", "Country": "NIGERIA"},
{"Code": "AC", "Country": "NICARAGUA"},
{"Code": "AC", "Country": "NETHERLANDS"},
{"Code": "AC", "Country": "NORWAY"},
{"Code": "AC", "Country": "NEPAL"},
{"Code": "AC", "Country": "NAURU"},
{"Code": "AC", "Country": "Neutral Zone"},
{"Code": "AC", "Country": "NIUE"},
{"Code": "AC", "Country": "NEW ZEALAND"},
{"Code": "AC", "Country": "OMAN"},
{"Code": "AC", "Country": "PANAMA"},
{"Code": "AC", "Country": "PERU"},
{"Code": "AC", "Country": "FRENCH POLYNESIA"},
{"Code": "AC", "Country": "PAPUA NEW GUINEA"},
{"Code": "AC", "Country": "PHILIPPINES"},
{"Code": "AC", "Country": "Philippines"},
{"Code": "AC", "Country": "PAKISTAN"},
{"Code": "AC", "Country": "POLAND"},
{"Code": "AC", "Country": "SAINT PIERRE AND MIQUELON"},
{"Code": "AC", "Country": "PITCAIRN"},
{"Code": "AC", "Country": "PUERTO RICO"},
{"Code": "AC", "Country": "PALESTINIAN TERRITORY, OCCUPIED"},
{"Code": "AC", "Country": "PORTUGAL"},
{"Code": "AC", "Country": "PALAU"},
{"Code": "AC", "Country": "PARAGUAY"},
{"Code": "AC", "Country": "QATAR"},
{"Code": "AC", "Country": "SERBIA"},
{"Code": "AC", "Country": "RUSSIAN FEDERATION"},
{"Code": "AC", "Country": "RWANDA"},
{"Code": "AC", "Country": "SAUDI ARABIA"},
{"Code": "AC", "Country": "SOLOMON ISLANDS"},
{"Code": "AC", "Country": "SEYCHELLES"},
{"Code": "AC", "Country": "SUDAN"},
{"Code": "AC", "Country": "SWEDEN"},
{"Code": "AC", "Country": "Finland"},
{"Code": "AC", "Country": "SINGAPORE"},
{"Code": "AC", "Country": "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA"},
{"Code": "AC", "Country": "SLOVENIA"},
{"Code": "AC", "Country": "SVALBARD AND JAN MAYEN"},
{"Code": "AC", "Country": "SLOVAKIA"},
{"Code": "AC", "Country": "SIERRA LEONE"},
{"Code": "AC", "Country": "SAN MARINO"},
{"Code": "AC", "Country": "SENEGAL"},
{"Code": "AC", "Country": "SOMALIA"},
{"Code": "AC", "Country": "SURINAME"},
{"Code": "AC", "Country": "SOUTH SUDAN"},
{"Code": "AC", "Country": "SAO TOME AND PRINCIPE"},
{"Code": "AC", "Country": "USSR"},
{"Code": "AC", "Country": "EL SALVADOR"},
{"Code": "AC", "Country": "SINT MAARTEN (DUTCH PART)"},
{"Code": "AC", "Country": "SYRIAN ARAB REPUBLIC"},
{"Code": "AC", "Country": "SWAZILAND"},
{"Code": "AC", "Country": "Tristan da Cunha"},
{"Code": "AC", "Country": "TURKS AND CAICOS ISLANDS"},
{"Code": "AC", "Country": "CHAD"},
{"Code": "AC", "Country": "FRENCH SOUTHERN TERRITORIES"},
{"Code": "AC", "Country": "TOGO"},
{"Code": "AC", "Country": "THAILAND"},
{"Code": "AC", "Country": "TAJIKISTAN"},
{"Code": "AC", "Country": "TOKELAU"},
{"Code": "AC", "Country": "TIMOR-LESTE"},
{"Code": "AC", "Country": "TURKMENISTAN"},
{"Code": "AC", "Country": "TUNISIA"},
{"Code": "AC", "Country": "TONGA"},
{"Code": "AC", "Country": "East Timor"},
{"Code": "AC", "Country": "TURKEY"},
{"Code": "AC", "Country": "TRINIDAD AND TOBAGO"},
{"Code": "AC", "Country": "TUVALU"},
{"Code": "AC", "Country": "TAIWAN, PROVINCE OF CHINA"},
{"Code": "AC", "Country": "TANZANIA, UNITED REPUBLIC OF"},
{"Code": "AC", "Country": "UKRAINE"},
{"Code": "AC", "Country": "UGANDA"},
{"Code": "AC", "Country": "United Kingdom"},
{"Code": "AC", "Country": "UNITED STATES MINOR OUTLYING ISLANDS"},
{"Code": "AC", "Country": "UNITED STATES"},
{"Code": "AC", "Country": "URUGUAY"},
{"Code": "AC", "Country": "UZBEKISTAN"},
{"Code": "AC", "Country": "HOLY SEE (VATICAN CITY STATE)"},
{"Code": "AC", "Country": "SAINT VINCENT AND THE GRENADINES"},
{"Code": "AC", "Country": "VENEZUELA, BOLIVARIAN REPUBLIC"},
{"Code": "AC", "Country": "VIRGIN ISLANDS, BRITISH"},
{"Code": "AC", "Country": "VIRGIN ISLANDS, U.S."},
{"Code": "AC", "Country": "VIET NAM"},
{"Code": "AC", "Country": "VANUATU"},
{"Code": "AC", "Country": "WALLIS AND FUTUNA"},
{"Code": "AC", "Country": "YEMEN"},
{"Code": "AC", "Country": "MAYOTTE"},
{"Code": "AC", "Country": "Yugoslavia"},
{"Code": "AC", "Country": "SOUTH AFRICA"},
{"Code": "AC", "Country": "ZAMBIA"},
{"Code": "AC", "Country": "Zaire"},
{"Code": "AC", "Country": "ZIMBABWE"}
]


LANGUAGES_ISO639_1 = [ {"Code": "aa", "Name": "Afar"},
{"Code": "ab", "Name": "Abkhazian"},
{"Code": "ae", "Name": "Avestan"},
{"Code": "af", "Name": "Afrikaans"},
{"Code": "ak", "Name": "Akan"},
{"Code": "am", "Name": "Amharic"},
{"Code": "an", "Name": "Aragonese"},
{"Code": "ar", "Name": "Arabic"},
{"Code": "as", "Name": "Assamese"},
{"Code": "av", "Name": "Avaric"},
{"Code": "ay", "Name": "Aymara"},
{"Code": "az", "Name": "Azerbaijani"},
{"Code": "ba", "Name": "Bashkir"},
{"Code": "be", "Name": "Belarusian"},
{"Code": "bg", "Name": "Bulgarian"},
{"Code": "bh", "Name": "languages"},
{"Code": "bi", "Name": "Bislama"},
{"Code": "bm", "Name": "Bambara"},
{"Code": "bn", "Name": "Bengali"},
{"Code": "bo", "Name": "Tibetan"},
{"Code": "br", "Name": "Breton"},
{"Code": "bs", "Name": "Bosnian"},
{"Code": "ca", "Name": "Catalan"},
{"Code": "ce", "Name": "Chechen"},
{"Code": "ch", "Name": "Chamorro"},
{"Code": "co", "Name": "Corsican"},
{"Code": "cr", "Name": "Cree"},
{"Code": "cs", "Name": "Czech"},
{"Code": "cu", "Name": "Church"},
{"Code": "cv", "Name": "Chuvash"},
{"Code": "cy", "Name": "Welsh"},
{"Code": "da", "Name": "Danish"},
{"Code": "de", "Name": "German"},
{"Code": "dv", "Name": "Dhivehi"},
{"Code": "dz", "Name": "Dzongkha"},
{"Code": "ee", "Name": "Ewe"},
{"Code": "el", "Name": "Greek"},
{"Code": "en", "Name": "English"},
{"Code": "eo", "Name": "Esperanto"},
{"Code": "es", "Name": "Spanish"},
{"Code": "et", "Name": "Estonian"},
{"Code": "eu", "Name": "Basque"},
{"Code": "fa", "Name": "Persian"},
{"Code": "ff", "Name": "Fulah"},
{"Code": "fi", "Name": "Finnish"},
{"Code": "fj", "Name": "Fijian"},
{"Code": "fo", "Name": "Faroese"},
{"Code": "fr", "Name": "French"},
{"Code": "fy", "Name": "Western"},
{"Code": "ga", "Name": "Irish"},
{"Code": "gd", "Name": "Scottish"},
{"Code": "gl", "Name": "Galician"},
{"Code": "gn", "Name": "Guarani"},
{"Code": "gu", "Name": "Gujarati"},
{"Code": "gv", "Name": "Manx"},
{"Code": "ha", "Name": "Hausa"},
{"Code": "he", "Name": "Hebrew"},
{"Code": "hi", "Name": "Hindi"},
{"Code": "ho", "Name": "Hiri"},
{"Code": "hr", "Name": "Croatian"},
{"Code": "ht", "Name": "Haitian"},
{"Code": "hu", "Name": "Hungarian"},
{"Code": "hy", "Name": "Armenian"},
{"Code": "hz", "Name": "Herero"},
{"Code": "ia", "Name": "Interlingua"},
{"Code": "id", "Name": "Indonesian"},
{"Code": "ie", "Name": "Interlingue"},
{"Code": "ig", "Name": "Igbo"},
{"Code": "ii", "Name": "Sichuan"},
{"Code": "ik", "Name": "Inupiaq"},
{"Code": "io", "Name": "Ido"},
{"Code": "is", "Name": "Icelandic"},
{"Code": "it", "Name": "Italian"},
{"Code": "iu", "Name": "Inuktitut"},
{"Code": "ja", "Name": "Japanese"},
{"Code": "jv", "Name": "Javanese"},
{"Code": "ka", "Name": "Georgian"},
{"Code": "kg", "Name": "Kongo"},
{"Code": "ki", "Name": "Kikuyu"},
{"Code": "kj", "Name": "Kuanyama"},
{"Code": "kk", "Name": "Kazakh"},
{"Code": "kl", "Name": "Kalaallisut"},
{"Code": "km", "Name": "Central"},
{"Code": "kn", "Name": "Kannada"},
{"Code": "ko", "Name": "Korean"},
{"Code": "kr", "Name": "Kanuri"},
{"Code": "ks", "Name": "Kashmiri"},
{"Code": "ku", "Name": "Kurdish"},
{"Code": "kv", "Name": "Komi"},
{"Code": "kw", "Name": "Cornish"},
{"Code": "ky", "Name": "Kirghiz"},
{"Code": "la", "Name": "Latin"},
{"Code": "lb", "Name": "Luxembourgish"},
{"Code": "lg", "Name": "Ganda"},
{"Code": "li", "Name": "Limburgan"},
{"Code": "ln", "Name": "Lingala"},
{"Code": "lo", "Name": "Lao"},
{"Code": "lt", "Name": "Lithuanian"},
{"Code": "lu", "Name": "Luba-Katanga"},
{"Code": "lv", "Name": "Latvian"},
{"Code": "mg", "Name": "Malagasy"},
{"Code": "mh", "Name": "Marshallese"},
{"Code": "mi", "Name": "Maori"},
{"Code": "mk", "Name": "Macedonian"},
{"Code": "ml", "Name": "Malayalam"},
{"Code": "mn", "Name": "Mongolian"},
{"Code": "mr", "Name": "Marathi"},
{"Code": "ms", "Name": "Malay"},
{"Code": "mt", "Name": "Maltese"},
{"Code": "my", "Name": "Burmese"},
{"Code": "na", "Name": "Nauru"},
{"Code": "nb", "Name": "Norwegian"},
{"Code": "nd", "Name": "North"},
{"Code": "ne", "Name": "Nepali"},
{"Code": "ng", "Name": "Ndonga"},
{"Code": "nl", "Name": "Dutch"},
{"Code": "nn", "Name": "Norwegian"},
{"Code": "no", "Name": "Norwegian"},
{"Code": "nr", "Name": "South"},
{"Code": "nv", "Name": "Navajo"},
{"Code": "ny", "Name": "Nyanja"},
{"Code": "oc", "Name": "Occitan"},
{"Code": "oj", "Name": "Ojibwa"},
{"Code": "om", "Name": "Oromo"},
{"Code": "or", "Name": "Oriya"},
{"Code": "os", "Name": "Ossetian"},
{"Code": "pa", "Name": "Panjabi"},
{"Code": "pi", "Name": "Pali"},
{"Code": "pl", "Name": "Polish"},
{"Code": "ps", "Name": "Pushto"},
{"Code": "pt", "Name": "Portuguese"},
{"Code": "qu", "Name": "Quechua"},
{"Code": "rm", "Name": "Romansh"},
{"Code": "rn", "Name": "Rundi"},
{"Code": "ro", "Name": "Romanian"},
{"Code": "ru", "Name": "Russian"},
{"Code": "rw", "Name": "Kinyarwanda"},
{"Code": "sa", "Name": "Sanskrit"},
{"Code": "sc", "Name": "Sardinian"},
{"Code": "sd", "Name": "Sindhi"},
{"Code": "se", "Name": "Northern"},
{"Code": "sg", "Name": "Sango"},
{"Code": "sh", "Name": "Serbo-Croatian"},
{"Code": "si", "Name": "Sinhala"},
{"Code": "sk", "Name": "Slovak"},
{"Code": "sl", "Name": "Slovenian"},
{"Code": "sm", "Name": "Samoan"},
{"Code": "sn", "Name": "Shona"},
{"Code": "so", "Name": "Somali"},
{"Code": "sq", "Name": "Albanian"},
{"Code": "sr", "Name": "Serbian"},
{"Code": "ss", "Name": "Swati"},
{"Code": "st", "Name": "Southern"},
{"Code": "su", "Name": "Sundanese"},
{"Code": "sv", "Name": "Swedish"},
{"Code": "sw", "Name": "Swahili"},
{"Code": "ta", "Name": "Tamil"},
{"Code": "te", "Name": "Telugu"},
{"Code": "tg", "Name": "Tajik"},
{"Code": "th", "Name": "Thai"},
{"Code": "ti", "Name": "Tigrinya"},
{"Code": "tk", "Name": "Turkmen"},
{"Code": "tl", "Name": "Tagalog"},
{"Code": "tn", "Name": "Tswana"},
{"Code": "to", "Name": "Tonga"},
{"Code": "tr", "Name": "Turkish"},
{"Code": "ts", "Name": "Tsonga"},
{"Code": "tt", "Name": "Tatar"},
{"Code": "tw", "Name": "Twi"},
{"Code": "ty", "Name": "Tahitian"},
{"Code": "ug", "Name": "Uighur"},
{"Code": "uk", "Name": "Ukrainian"},
{"Code": "ur", "Name": "Urdu"},
{"Code": "uz", "Name": "Uzbek"},
{"Code": "ve", "Name": "Venda"},
{"Code": "vi", "Name": "Vietnamese"},
{"Code": "vo", "Name": "Volap"},
{"Code": "wa", "Name": "Walloon"},
{"Code": "wo", "Name": "Wolof"},
{"Code": "xh", "Name": "Xhosa"},
{"Code": "yi", "Name": "Yiddish"},
{"Code": "yo", "Name": "Yoruba"},
{"Code": "za", "Name": "Zhuang"},
{"Code": "zh", "Name": "Chinese"},
{"Code": "zu", "Name": "Zulu"}
]